version: "3.2"
networks: 
  simulacion_net:
    ipam: 
      driver: default
      config: 
        - subnet: 172.29.0.0/16
services:
  db_simulacion:
    container_name: postgres-simulacion
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=simulacion
      - POSTGRES_PASSWORD=demo123456
      - PGDATA=/data/postgres
    volumes:
      - ./postgres-data:/data/postgres
      - ./sql/createdatabase.sql:/docker-entrypoint-initdb.d/createdatabase.sql
    ports:
      - "5432:5432"
    networks:
      simulacion_net:
        ipv4_address: 172.29.1.3

  backend_simulacion:
    container_name: backend-simulacion
    build: ./build/backend
    ports:
      - '5500:5500'
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - db_simulacion
    networks: 
      simulacion_net:
        ipv4_address: 172.29.1.2

  frontend_simulacion:
    container_name: frontend-simulacion
    build: ./build/frontend
    ports:
      - '4000:4000'
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend_simulacion
    tty: true
    networks: 
      simulacion_net:
        ipv4_address: 172.29.1.1
